Integrate docker-compose
Ponjimon/vrising-docker pull request #5
Opened 2022-05-23 19:14 UTC by theCrius

2022-05-23 21:31 UTC, Ponjimon commented
Nice, thank you. Although there still is the issue with conflicting permissions due to the bind mount volume. It crashes for me starting it with docker-compose. Any idea how we could fix this?

2022-05-23 23:54 UTC, theCrius commented
Can you paste the exact error log? It simply start on a fresh ubuntu 20.04 vm with only docker and docker-compose installed.

be sure to follow this guide: 
[Install Docker](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04)
[Install Docker-Compose](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-20-04)

2022-05-24 17:01 UTC, Ponjimon commented
The error is this:

```
UnauthorizedAccessException: Access to the path "Z:\vrising\server-data\Saves" is denied.
  at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00000] in <00000000000000000000000000000000>:0
``` 

I think it's because of a mismatch between host and container permissions due to the Docker image assuming a GID and UID of 1000

2022-05-24 19:36 UTC, theCrius commented
mhm, that is weird is definitely having something to do with the volume, you are right. Can you tell me what are the specs of your host? specifically which linux distro and what username are you connecting to with?

2022-05-24 20:16 UTC, Ponjimon commented
It's running inside the devcontainer (see `.devcontainer` folder in this repo).

2022-05-24 23:38 UTC, theCrius commented
As far as I know, the .devcontainer is something used to quickly spin a docker container from vscode so that you can manage and develop in an isolated environment. If it causes any issue, it's related to that and not the docker-compose itself.

Have you run this from a vscode instance running? On linux or windows (and if windows, WSL or host OS)?

2022-05-25 09:33 UTC, Ponjimon commented
Oh, don't get me wrong, it has nothing to do with the compose file. I'm gonna merge your PR soon anyway :)

2022-05-26 01:47 UTC, Ponjimon commented on docker-compose.yaml
> +        STEAM_EPOC:
I think you can remove this again. When I initially created the Dockerfile, I used another Dockerfile as the base and this was just a remnant.

2022-05-26 01:48 UTC, Ponjimon commented
I updated the Docker image in `main` along with the readme. Once you update your branch, I will merge it

2022-05-26 09:45 UTC, theCrius commented
Should be all good now, double check the readme just to be sure I haven't deleted the wrong lines while resolving the conflicts and we are good to go :)

2022-05-26 13:53 UTC, Ponjimon commented
You removed your changes to the readme again :)

2022-05-26 13:54 UTC, theCrius commented
FFfffff.... i'm having one of those days, bear with me

2022-05-26 13:59 UTC, theCrius commented
All done now :)

2022-05-26 14:06 UTC, Ponjimon requested changes
Just some typos and then we're good to go

2022-05-26 14:06 UTC, Ponjimon commented on README.md
> + Alternatively, you can use `docker-compose`. Simply run `docker-compose up -d`to spin up a container. The `docker-compose.yaml` file assumes that there is a directory `${home}/vrising-server` in whi
```suggestion
 Alternatively, you can use `docker-compose`. Simply run `docker-compose up -d` to spin up a container. The `docker-compose.yaml` file assumes that there is a directory `${HOME}/vrising-server` in which the container will mount a volume and store the saves where you can add your custom settings.
```

2022-05-26 14:18 UTC, Ponjimon approved these changes

2022-05-26 14:18 UTC, merged